const followers = [
  {
    login: "tarasis",
    id: 3006,
    node_id: "MDQ6VXNlcjMwMDY=",
    avatar_url: "https://avatars.githubusercontent.com/u/3006?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/tarasis",
    html_url: "https://github.com/tarasis",
    followers_url: "https://api.github.com/users/tarasis/followers",
    following_url:
      "https://api.github.com/users/tarasis/following{/other_user}",
    gists_url: "https://api.github.com/users/tarasis/gists{/gist_id}",
    starred_url: "https://api.github.com/users/tarasis/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/tarasis/subscriptions",
    organizations_url: "https://api.github.com/users/tarasis/orgs",
    repos_url: "https://api.github.com/users/tarasis/repos",
    events_url: "https://api.github.com/users/tarasis/events{/privacy}",
    received_events_url: "https://api.github.com/users/tarasis/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "elvan",
    id: 35147,
    node_id: "MDQ6VXNlcjM1MTQ3",
    avatar_url: "https://avatars.githubusercontent.com/u/35147?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/elvan",
    html_url: "https://github.com/elvan",
    followers_url: "https://api.github.com/users/elvan/followers",
    following_url: "https://api.github.com/users/elvan/following{/other_user}",
    gists_url: "https://api.github.com/users/elvan/gists{/gist_id}",
    starred_url: "https://api.github.com/users/elvan/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/elvan/subscriptions",
    organizations_url: "https://api.github.com/users/elvan/orgs",
    repos_url: "https://api.github.com/users/elvan/repos",
    events_url: "https://api.github.com/users/elvan/events{/privacy}",
    received_events_url: "https://api.github.com/users/elvan/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "cksachdev",
    id: 37770,
    node_id: "MDQ6VXNlcjM3Nzcw",
    avatar_url: "https://avatars.githubusercontent.com/u/37770?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/cksachdev",
    html_url: "https://github.com/cksachdev",
    followers_url: "https://api.github.com/users/cksachdev/followers",
    following_url:
      "https://api.github.com/users/cksachdev/following{/other_user}",
    gists_url: "https://api.github.com/users/cksachdev/gists{/gist_id}",
    starred_url:
      "https://api.github.com/users/cksachdev/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/cksachdev/subscriptions",
    organizations_url: "https://api.github.com/users/cksachdev/orgs",
    repos_url: "https://api.github.com/users/cksachdev/repos",
    events_url: "https://api.github.com/users/cksachdev/events{/privacy}",
    received_events_url:
      "https://api.github.com/users/cksachdev/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "undencem",
    id: 40747,
    node_id: "MDQ6VXNlcjQwNzQ3",
    avatar_url: "https://avatars.githubusercontent.com/u/40747?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/undencem",
    html_url: "https://github.com/undencem",
    followers_url: "https://api.github.com/users/undencem/followers",
    following_url:
      "https://api.github.com/users/undencem/following{/other_user}",
    gists_url: "https://api.github.com/users/undencem/gists{/gist_id}",
    starred_url: "https://api.github.com/users/undencem/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/undencem/subscriptions",
    organizations_url: "https://api.github.com/users/undencem/orgs",
    repos_url: "https://api.github.com/users/undencem/repos",
    events_url: "https://api.github.com/users/undencem/events{/privacy}",
    received_events_url:
      "https://api.github.com/users/undencem/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "pauloesantos",
    id: 46524,
    node_id: "MDQ6VXNlcjQ2NTI0",
    avatar_url: "https://avatars.githubusercontent.com/u/46524?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/pauloesantos",
    html_url: "https://github.com/pauloesantos",
    followers_url: "https://api.github.com/users/pauloesantos/followers",
    following_url:
      "https://api.github.com/users/pauloesantos/following{/other_user}",
    gists_url: "https://api.github.com/users/pauloesantos/gists{/gist_id}",
    starred_url:
      "https://api.github.com/users/pauloesantos/starred{/owner}{/repo}",
    subscriptions_url:
      "https://api.github.com/users/pauloesantos/subscriptions",
    organizations_url: "https://api.github.com/users/pauloesantos/orgs",
    repos_url: "https://api.github.com/users/pauloesantos/repos",
    events_url: "https://api.github.com/users/pauloesantos/events{/privacy}",
    received_events_url:
      "https://api.github.com/users/pauloesantos/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "arthu",
    id: 55780,
    node_id: "MDQ6VXNlcjU1Nzgw",
    avatar_url: "https://avatars.githubusercontent.com/u/55780?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/arthu",
    html_url: "https://github.com/arthu",
    followers_url: "https://api.github.com/users/arthu/followers",
    following_url: "https://api.github.com/users/arthu/following{/other_user}",
    gists_url: "https://api.github.com/users/arthu/gists{/gist_id}",
    starred_url: "https://api.github.com/users/arthu/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/arthu/subscriptions",
    organizations_url: "https://api.github.com/users/arthu/orgs",
    repos_url: "https://api.github.com/users/arthu/repos",
    events_url: "https://api.github.com/users/arthu/events{/privacy}",
    received_events_url: "https://api.github.com/users/arthu/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "wxqfree",
    id: 57497,
    node_id: "MDQ6VXNlcjU3NDk3",
    avatar_url: "https://avatars.githubusercontent.com/u/57497?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/wxqfree",
    html_url: "https://github.com/wxqfree",
    followers_url: "https://api.github.com/users/wxqfree/followers",
    following_url:
      "https://api.github.com/users/wxqfree/following{/other_user}",
    gists_url: "https://api.github.com/users/wxqfree/gists{/gist_id}",
    starred_url: "https://api.github.com/users/wxqfree/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/wxqfree/subscriptions",
    organizations_url: "https://api.github.com/users/wxqfree/orgs",
    repos_url: "https://api.github.com/users/wxqfree/repos",
    events_url: "https://api.github.com/users/wxqfree/events{/privacy}",
    received_events_url: "https://api.github.com/users/wxqfree/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "mainick",
    id: 67373,
    node_id: "MDQ6VXNlcjY3Mzcz",
    avatar_url: "https://avatars.githubusercontent.com/u/67373?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/mainick",
    html_url: "https://github.com/mainick",
    followers_url: "https://api.github.com/users/mainick/followers",
    following_url:
      "https://api.github.com/users/mainick/following{/other_user}",
    gists_url: "https://api.github.com/users/mainick/gists{/gist_id}",
    starred_url: "https://api.github.com/users/mainick/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/mainick/subscriptions",
    organizations_url: "https://api.github.com/users/mainick/orgs",
    repos_url: "https://api.github.com/users/mainick/repos",
    events_url: "https://api.github.com/users/mainick/events{/privacy}",
    received_events_url: "https://api.github.com/users/mainick/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "esin",
    id: 69767,
    node_id: "MDQ6VXNlcjY5NzY3",
    avatar_url: "https://avatars.githubusercontent.com/u/69767?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/esin",
    html_url: "https://github.com/esin",
    followers_url: "https://api.github.com/users/esin/followers",
    following_url: "https://api.github.com/users/esin/following{/other_user}",
    gists_url: "https://api.github.com/users/esin/gists{/gist_id}",
    starred_url: "https://api.github.com/users/esin/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/esin/subscriptions",
    organizations_url: "https://api.github.com/users/esin/orgs",
    repos_url: "https://api.github.com/users/esin/repos",
    events_url: "https://api.github.com/users/esin/events{/privacy}",
    received_events_url: "https://api.github.com/users/esin/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "yxm0513",
    id: 73510,
    node_id: "MDQ6VXNlcjczNTEw",
    avatar_url: "https://avatars.githubusercontent.com/u/73510?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/yxm0513",
    html_url: "https://github.com/yxm0513",
    followers_url: "https://api.github.com/users/yxm0513/followers",
    following_url:
      "https://api.github.com/users/yxm0513/following{/other_user}",
    gists_url: "https://api.github.com/users/yxm0513/gists{/gist_id}",
    starred_url: "https://api.github.com/users/yxm0513/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/yxm0513/subscriptions",
    organizations_url: "https://api.github.com/users/yxm0513/orgs",
    repos_url: "https://api.github.com/users/yxm0513/repos",
    events_url: "https://api.github.com/users/yxm0513/events{/privacy}",
    received_events_url: "https://api.github.com/users/yxm0513/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "GavinBryan",
    id: 76623,
    node_id: "MDQ6VXNlcjc2NjIz",
    avatar_url: "https://avatars.githubusercontent.com/u/76623?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/GavinBryan",
    html_url: "https://github.com/GavinBryan",
    followers_url: "https://api.github.com/users/GavinBryan/followers",
    following_url:
      "https://api.github.com/users/GavinBryan/following{/other_user}",
    gists_url: "https://api.github.com/users/GavinBryan/gists{/gist_id}",
    starred_url:
      "https://api.github.com/users/GavinBryan/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/GavinBryan/subscriptions",
    organizations_url: "https://api.github.com/users/GavinBryan/orgs",
    repos_url: "https://api.github.com/users/GavinBryan/repos",
    events_url: "https://api.github.com/users/GavinBryan/events{/privacy}",
    received_events_url:
      "https://api.github.com/users/GavinBryan/received_events",
    type: "User",
    site_admin: false,
  },
];
export default followers;
